Correct multiple swig version location for python binding compilation
openbabel/openbabel pull request #1665
Opened 2017-10-12 20:26 UTC by jjgomera

I use debian stretch and for get a python binding i've had problem to install from pip, installation always search for swig program and in my system the installed version is the swig3.0, so i configure the setup to search between both version to choose always any installed version.

2017-10-19 22:50 UTC, ghutchis requested changes

2017-10-19 22:50 UTC, ghutchis commented on scripts/python/setup.py
> +#!/usr/bin/env python3
I don't want to make that change. If someone still has Python 2, or a Python binary "python" (e.g. my Python 3.6 binary) it will fail.

2017-10-19 22:50 UTC, ghutchis commented on scripts/python/setup.py
> -        include_dirs = '/usr/local/include/openbabel-2.0'
This is preferred.

2017-10-19 22:50 UTC, ghutchis commented on scripts/python/setup.py
> -        version = pkgconfig('openbabel-2.0', '--modversion')
How about you try both openbabel-2.0 and openbabel?

2017-10-19 22:50 UTC, ghutchis commented on scripts/python/setup.py
> +    def find_swig(self):
This is fine. Probably worth finding out other names for SWIG binaries..

2017-10-22 20:16 UTC, baoilleach commented
There seem to be several changes here, unrelated to the problem the patch is intended to solve. Which makes me uneasy.

2026-05-14 20:50 UTC, ghutchis commented
I'm closing this - it's moot with modern SWIG and Python. Thanks

2026-05-14 20:50 UTC, closed without merging